name: CI

on:
  pull_request:
    branches: [ "main"]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Yarn add eslint
        run: |
          yarn
          yarn add @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run eslint
        run: yarn lint
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true
      
      - name: Upload results to github
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  test:
    runs-on: ubuntu-latest
    needs: eslint

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest, windows-2016]
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
   
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: run tests
      run: |
        yarn
        yarn run test

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
      
